name: daily

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: inst.sh
        env:
          INST_SH: ${{ secrets.INST_SH }}
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: bash -c "$INST_SH"
      - name: daily.sh
        env:
          DAILY_SH: ${{ secrets.DAILY_SH }}
          RCLONE_CONFIG_PASS: ${{ secrets.RCLONE_CONFIG_PASS }}
          GH_TOKEN: ${{ secrets.TOKEN_REPO }}
        run: bash -c "$DAILY_SH"
      - name: save_conf.sh
        env:
          SAVE_CONF_SH: ${{ secrets.SAVE_CONF_SH }}
          GH_TOKEN: ${{ secrets.TOKEN_REPO }}
        run: bash -c "$SAVE_CONF_SH"
