name: Docker

on:
  workflow_dispatch:
    inputs:
      distributed:
        description: Multiple runners
        type: boolean
        default: false
      repo:
        description: Repo
        required: true
      tag:
        description: Tag
        required: true
      branch:
        description: Branch
        required: true
        default: dockerfile
      latest:
        type: boolean
        default: true
      cacheKey:
        description: Cache Key
        default: '0'
      cleanUp:
        type: boolean
        description: Clean Up ghcr.io

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ inputs.repo }}
permissions:
  contents: read
  packages: write

jobs:

  build:
    if: ${{ !inputs.distributed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.TOKEN_REPO }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=raw,value=latest,enable=${{ inputs.latest }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ inputs.tag }}
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ inputs.repo }}-${{ inputs.tag }}-${{ inputs.cacheKey }}
          cache-to: type=gha,mode=max,scope=${{ inputs.repo }}-${{ inputs.tag }}-${{ inputs.cacheKey }}
          # https://github.com/docker/build-push-action/issues/820#issuecomment-1455687416
          # Dot not push the extra manifest of unkown OS/Arch.
          provenance: false

      - uses: dataaxiom/ghcr-cleanup-action@v1
        if: ${{ inputs.cleanUp }}
        with:
          owner: ${{ env.REGISTRY_USERNAME }}
          repository: ${{ inputs.repo }}
          package: ${{ inputs.repo }}
          token: ${{ secrets.TOKEN_REPO }}

  distributed:
    if: ${{ inputs.distributed }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner || 'ubuntu-latest' }}
    steps:
      - name: Increase swap for ARM runner
        if: ${{ endsWith(matrix.runner, 'arm') }}
        run: |
          free -h
          SWAP_PATH="$(swapon --show=NAME --noheadings)"
          sudo swapoff "$SWAP_PATH"
          sudo rm "$SWAP_PATH"
          sudo fallocate -l 16G "$SWAP_PATH"
          sudo chmod 600 "$SWAP_PATH"
          sudo mkswap "$SWAP_PATH"
          sudo swapon "$SWAP_PATH"
          free -h
          swapon

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.TOKEN_REPO }}

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=raw,value=latest,enable=${{ inputs.latest }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ inputs.tag }}
          context: .
          platforms: ${{ matrix.platform }}
          # labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ inputs.repo }}-${{ inputs.tag }}-${{ inputs.cacheKey }}-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=max,scope=${{ inputs.repo }}-${{ inputs.tag }}-${{ inputs.cacheKey }}-${{ env.PLATFORM_PAIR }}
          # https://github.com/docker/build-push-action/issues/820#issuecomment-1455687416
          # Dot not push the extra manifest of unkown OS/Arch.
          provenance: false

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: ${{ inputs.distributed }}
    needs: [distributed]
    runs-on: ubuntu-latest
    steps:
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=raw,value=latest,enable=${{ inputs.latest }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - uses: dataaxiom/ghcr-cleanup-action@v1
        if: ${{ inputs.cleanUp }}
        with:
          owner: ${{ env.REGISTRY_USERNAME }}
          repository: ${{ inputs.repo }}
          package: ${{ inputs.repo }}
          token: ${{ secrets.TOKEN_REPO }}
